<?php
/**
 * Copyright (c) 2013-2014 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2014 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<script type="text/javascript" src="<?php echo $this->getCollectorUrl() ?>"></script>
<script type="text/javascript">
document.observe("dom:loaded", function() {
	var field = '<?php echo $this->getField() ?>';
	var mappingField = '<?php echo $this->getMappingField() ?>';
	$('co-payment-form').insert(field);
	$('co-payment-form').insert(mappingField);
	/**
	 * Wrapper function around the PayPal Express review submit button.
	 * Populates form with JSC data and then proceeds with existing
	 * event handling.
	 * @param function originalFn Original event handler
	 */
	var jscWrapper = function jscWrapper(originalFn) {
		try {
			<?php echo $this->getCall() ?>
		} catch(error) {
		}
		// re-enable the payment form - JSC fields disabled when finishing the
		// payment step
		$('<?php echo $this->getFieldName() ?>').enable();
		$('<?php echo $this->getMappingFieldName() ?>').enable();
		// call the original, wrapped function
		originalFn.call(this);
	};
	// wrap the Review.save method with JSC collection
	Review.prototype.save = Review.prototype.save.wrap(jscWrapper);
});
</script>
