<?php
/**
 * Copyright (c) 2013-2016 Radial, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2016 Radial, Inc. (http://www.radial.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<script type="text/javascript" src="<?php echo $this->getCollectorUrl() ?>"></script>
<script type="text/javascript">
document.observe("dom:loaded", function() {
	var field = '<?php echo $this->getField() ?>';
	var mappingField = '<?php echo $this->getMappingField() ?>';
	$('edit_form').insert(field);
	$('edit_form').insert(mappingField);
	/**
	 * Wrapper function around the order submit button.
	 * Populates form with JSC data and then proceeds with existing
	 * event handling.
	 * @param function originalFn Original event handler
	 */
	var jscWrapper = function jscWrapper(originalFn) {
		try {
			<?php echo $this->getCall() ?>
		} catch(error) {
		}
		// call the original, wrapped function
		originalFn.call(this);
	};
	// wrap the Order.submit method with JSC collection
	varienForm.prototype.submit = varienForm.prototype.submit.wrap(jscWrapper);
});
</script>
