#!/usr/bin/env bash

repo="$PWD"

echo 'Setting up composer'
cd ../build
cp "$repo/circle-ci/composer.json" .
composer --global --no-interaction config repositories.this path "$repo"
# Firegento has to come last
composer --global --no-interaction config repositories.firegento composer https://packages.firegento.com
composer --no-interaction --no-update require \
        'radial/magento-fraud-risk:*@dev'
composer --no-interaction --prefer-source update

echo 'Removing base url from database'
mysql --user ubuntu -e 'DELETE FROM core_config_data WHERE path LIKE "web/%secure/base_url"\g' circle_test

echo 'Configuring Magento for testing'
cp "$repo"/tests/composer.xml app/etc/
cp "$repo"/circle-ci/local.xml.phpunit app/etc/
cp "$repo"/tests/phpunit.xml.dist .
